//! Converter between Amazon Rose Forest and YumeiCHAIN knowledge formats
//!
//! This module provides utilities for converting between the internal
//! knowledge representation and YumeiCHAIN's standardized format.

use std::time::{SystemTime, UNIX_EPOCH};
use chrono::{DateTime, Utc};
use crate::knowledge::representation::{Knowledge, KnowledgeMetadata};
use crate::knowledge::crdt::{CRDTKnowledge, AgentId};
use super::schema::{
    KnowledgePackage, Content, Confidence, ReasoningTrace, Metadata, Trust, Votes
};

/// Converter for knowledge formats
pub struct KnowledgeConverter;

impl KnowledgeConverter {
    /// Convert from Amazon Rose Forest Knowledge to YumeiCHAIN KnowledgePackage
    pub fn to_yumechain(
        knowledge: &Knowledge,
        agent_id: &str,
        reasoning_method: &str,
        reasoning_steps: Vec<String>
    ) -> KnowledgePackage {
        // Convert content
        let content_text = match std::str::from_utf8(&knowledge.content) {
            Ok(text) => text.to_string(),
            Err(_) => String::from_utf8_lossy(&knowledge.content).to_string(),
        };

        // Convert metadata
        let created_at = DateTime::<Utc>::from_timestamp(
            knowledge.metadata.timestamp as i64, 0
        ).unwrap_or_else(|| Utc::now());

        KnowledgePackage {
            knowledge_id: Some(knowledge.id.clone()),
            version_id: None, // Will be generated by YumeiCHAIN
            content: Content {
                text: content_text,
                format: "markdown".to_string(),
                generated_by: agent_id.to_string(),
            },
            confidence: Confidence {
                overall: knowledge.metadata.confidence,
                statements: None,
            },
            reasoning_trace: ReasoningTrace {
                method: reasoning_method.to_string(),
                steps: reasoning_steps,
                alternatives: None,
            },
            metadata: Metadata {
                domain: knowledge.metadata.source.clone(),
                subdomains: None,
                type_: "concept".to_string(), // Default type
                tags: Some(knowledge.metadata.tags.clone()),
                source_citations: None,
                related_knowledge: None,
                created_at: Some(created_at),
                updated_at: Some(Utc::now()),
            },
            trust: None, // Will be managed by YumeiCHAIN
        }
    }

    /// Convert from YumeiCHAIN KnowledgePackage to Amazon Rose Forest Knowledge
    pub fn from_yumechain(package: &KnowledgePackage) -> Knowledge {
        // Convert content
        let content = package.content.text.as_bytes().to_vec();

        // Convert metadata
        let timestamp = match package.metadata.created_at {
            Some(dt) => dt.timestamp() as u64,
            None => SystemTime::now()
                .duration_since(UNIX_EPOCH)
                .unwrap_or_default()
                .as_secs(),
        };

        // Extract tags
        let tags = package.metadata.tags.clone().unwrap_or_default();

        // Create knowledge metadata
        let metadata = KnowledgeMetadata {
            timestamp,
            source: package.metadata.domain.clone(),
            confidence: package.confidence.overall,
            tags,
        };

        // Create knowledge
        Knowledge {
            id: package.knowledge_id.clone().unwrap_or_else(|| uuid::Uuid::new_v4().to_string()),
            content,
            metadata,
            vectors: Vec::new(), // Vectors would need to be generated separately
        }
    }

    /// Convert from YumeiCHAIN KnowledgePackage to Amazon Rose Forest CRDTKnowledge
    pub fn to_crdt_knowledge(package: &KnowledgePackage, agent_id: &str) -> CRDTKnowledge {
        let knowledge = Self::from_yumechain(package);
        CRDTKnowledge::new(knowledge, AgentId(agent_id.to_string()))
    }

    /// Create a reasoning trace from a knowledge processing operation
    pub fn create_reasoning_trace(steps: Vec<String>) -> ReasoningTrace {
        ReasoningTrace {
            method: "chain-of-thought".to_string(),
            steps,
            alternatives: None,
        }
    }
}